# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/projects/thomas_moore/xilinx/proc/proc.cache/wt [current_project]
set_property parent.project_path Z:/projects/thomas_moore/xilinx/proc/proc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib {
  Z:/projects/thomas_moore/pck_myhdl_090.vhd
  Z:/projects/thomas_moore/proc.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/projects/thomas_moore/proc.xdc
set_property used_in_implementation false [get_files Z:/projects/thomas_moore/proc.xdc]


synth_design -top proc -part xc7a100tcsg324-1


write_checkpoint -force -noxdef proc.dcp

catch { report_utilization -file proc_utilization_synth.rpt -pb proc_utilization_synth.pb }
